/**
 * generated by Xtext 2.13.0
 */
package br.dslcross.crossplatform;

import br.dslcross.crossplatform.CrossPlatformStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class CrossPlatformStandaloneSetup extends CrossPlatformStandaloneSetupGenerated {
  public static void doSetup() {
    new CrossPlatformStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
