/*
 * generated by Xtext 2.13.0
 */
package br.dslcross.crossplatform


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class CrossPlatformStandaloneSetup extends CrossPlatformStandaloneSetupGenerated {

	def static void doSetup() {
		new CrossPlatformStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
