/**
 * generated by Xtext 2.24.0
 */
package br.dslcross.crossplatform.crossPlatform;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Abrev Cmd</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.dslcross.crossplatform.crossPlatform.AbrevCmd#getExpr1 <em>Expr1</em>}</li>
 *   <li>{@link br.dslcross.crossplatform.crossPlatform.AbrevCmd#getOpIn <em>Op In</em>}</li>
 *   <li>{@link br.dslcross.crossplatform.crossPlatform.AbrevCmd#getExpr2 <em>Expr2</em>}</li>
 *   <li>{@link br.dslcross.crossplatform.crossPlatform.AbrevCmd#getExpr3 <em>Expr3</em>}</li>
 * </ul>
 *
 * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getAbrevCmd()
 * @model
 * @generated
 */
public interface AbrevCmd extends CommandOperation
{
  /**
   * Returns the value of the '<em><b>Expr1</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr1</em>' reference.
   * @see #setExpr1(Attribute)
   * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getAbrevCmd_Expr1()
   * @model
   * @generated
   */
  Attribute getExpr1();

  /**
   * Sets the value of the '{@link br.dslcross.crossplatform.crossPlatform.AbrevCmd#getExpr1 <em>Expr1</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr1</em>' reference.
   * @see #getExpr1()
   * @generated
   */
  void setExpr1(Attribute value);

  /**
   * Returns the value of the '<em><b>Op In</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op In</em>' attribute.
   * @see #setOpIn(String)
   * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getAbrevCmd_OpIn()
   * @model
   * @generated
   */
  String getOpIn();

  /**
   * Sets the value of the '{@link br.dslcross.crossplatform.crossPlatform.AbrevCmd#getOpIn <em>Op In</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op In</em>' attribute.
   * @see #getOpIn()
   * @generated
   */
  void setOpIn(String value);

  /**
   * Returns the value of the '<em><b>Expr2</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr2</em>' reference.
   * @see #setExpr2(Attribute)
   * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getAbrevCmd_Expr2()
   * @model
   * @generated
   */
  Attribute getExpr2();

  /**
   * Sets the value of the '{@link br.dslcross.crossplatform.crossPlatform.AbrevCmd#getExpr2 <em>Expr2</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr2</em>' reference.
   * @see #getExpr2()
   * @generated
   */
  void setExpr2(Attribute value);

  /**
   * Returns the value of the '<em><b>Expr3</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr3</em>' containment reference.
   * @see #setExpr3(ExprArit)
   * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getAbrevCmd_Expr3()
   * @model containment="true"
   * @generated
   */
  ExprArit getExpr3();

  /**
   * Sets the value of the '{@link br.dslcross.crossplatform.crossPlatform.AbrevCmd#getExpr3 <em>Expr3</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr3</em>' containment reference.
   * @see #getExpr3()
   * @generated
   */
  void setExpr3(ExprArit value);

} // AbrevCmd
