/**
 * generated by Xtext 2.24.0
 */
package br.dslcross.crossplatform.crossPlatform;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Attribute Call</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.dslcross.crossplatform.crossPlatform.AttributeCall#getName <em>Name</em>}</li>
 *   <li>{@link br.dslcross.crossplatform.crossPlatform.AttributeCall#getCol1 <em>Col1</em>}</li>
 *   <li>{@link br.dslcross.crossplatform.crossPlatform.AttributeCall#getArray <em>Array</em>}</li>
 *   <li>{@link br.dslcross.crossplatform.crossPlatform.AttributeCall#getCol2 <em>Col2</em>}</li>
 *   <li>{@link br.dslcross.crossplatform.crossPlatform.AttributeCall#getVAtr2 <em>VAtr2</em>}</li>
 *   <li>{@link br.dslcross.crossplatform.crossPlatform.AttributeCall#getCol <em>Col</em>}</li>
 *   <li>{@link br.dslcross.crossplatform.crossPlatform.AttributeCall#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getAttributeCall()
 * @model
 * @generated
 */
public interface AttributeCall extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getAttributeCall_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link br.dslcross.crossplatform.crossPlatform.AttributeCall#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Col1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Col1</em>' attribute.
   * @see #setCol1(String)
   * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getAttributeCall_Col1()
   * @model
   * @generated
   */
  String getCol1();

  /**
   * Sets the value of the '{@link br.dslcross.crossplatform.crossPlatform.AttributeCall#getCol1 <em>Col1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Col1</em>' attribute.
   * @see #getCol1()
   * @generated
   */
  void setCol1(String value);

  /**
   * Returns the value of the '<em><b>Array</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Array</em>' attribute.
   * @see #setArray(int)
   * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getAttributeCall_Array()
   * @model
   * @generated
   */
  int getArray();

  /**
   * Sets the value of the '{@link br.dslcross.crossplatform.crossPlatform.AttributeCall#getArray <em>Array</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Array</em>' attribute.
   * @see #getArray()
   * @generated
   */
  void setArray(int value);

  /**
   * Returns the value of the '<em><b>Col2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Col2</em>' attribute.
   * @see #setCol2(String)
   * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getAttributeCall_Col2()
   * @model
   * @generated
   */
  String getCol2();

  /**
   * Sets the value of the '{@link br.dslcross.crossplatform.crossPlatform.AttributeCall#getCol2 <em>Col2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Col2</em>' attribute.
   * @see #getCol2()
   * @generated
   */
  void setCol2(String value);

  /**
   * Returns the value of the '<em><b>VAtr2</b></em>' containment reference list.
   * The list contents are of type {@link br.dslcross.crossplatform.crossPlatform.AttribID}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>VAtr2</em>' containment reference list.
   * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getAttributeCall_VAtr2()
   * @model containment="true"
   * @generated
   */
  EList<AttribID> getVAtr2();

  /**
   * Returns the value of the '<em><b>Col</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Col</em>' attribute list.
   * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getAttributeCall_Col()
   * @model unique="false"
   * @generated
   */
  EList<String> getCol();

  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference list.
   * The list contents are of type {@link br.dslcross.crossplatform.crossPlatform.ExprL}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference list.
   * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getAttributeCall_Value()
   * @model containment="true"
   * @generated
   */
  EList<ExprL> getValue();

} // AttributeCall
