/**
 * generated by Xtext 2.24.0
 */
package br.dslcross.crossplatform.crossPlatform;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage
 * @generated
 */
public interface CrossPlatformFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  CrossPlatformFactory eINSTANCE = br.dslcross.crossplatform.crossPlatform.impl.CrossPlatformFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Domainmodel</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Domainmodel</em>'.
   * @generated
   */
  Domainmodel createDomainmodel();

  /**
   * Returns a new object of class '<em>Abstract Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Abstract Element</em>'.
   * @generated
   */
  AbstractElement createAbstractElement();

  /**
   * Returns a new object of class '<em>Package Declaration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Package Declaration</em>'.
   * @generated
   */
  PackageDeclaration createPackageDeclaration();

  /**
   * Returns a new object of class '<em>Import</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Import</em>'.
   * @generated
   */
  Import createImport();

  /**
   * Returns a new object of class '<em>Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Type</em>'.
   * @generated
   */
  Type createType();

  /**
   * Returns a new object of class '<em>Platform Decl</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Platform Decl</em>'.
   * @generated
   */
  PlatformDecl createPlatformDecl();

  /**
   * Returns a new object of class '<em>Global Old</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Global Old</em>'.
   * @generated
   */
  GlobalOld createGlobalOld();

  /**
   * Returns a new object of class '<em>Global Entity</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Global Entity</em>'.
   * @generated
   */
  GlobalEntity createGlobalEntity();

  /**
   * Returns a new object of class '<em>Global</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Global</em>'.
   * @generated
   */
  Global createGlobal();

  /**
   * Returns a new object of class '<em>Deploy</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Deploy</em>'.
   * @generated
   */
  Deploy createDeploy();

  /**
   * Returns a new object of class '<em>Platform</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Platform</em>'.
   * @generated
   */
  Platform createPlatform();

  /**
   * Returns a new object of class '<em>Entity Esp</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Entity Esp</em>'.
   * @generated
   */
  EntityEsp createEntityEsp();

  /**
   * Returns a new object of class '<em>Data Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Data Type</em>'.
   * @generated
   */
  DataType createDataType();

  /**
   * Returns a new object of class '<em>Entity</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Entity</em>'.
   * @generated
   */
  Entity createEntity();

  /**
   * Returns a new object of class '<em>Command Feature</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Command Feature</em>'.
   * @generated
   */
  CommandFeature createCommandFeature();

  /**
   * Returns a new object of class '<em>Command Plat</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Command Plat</em>'.
   * @generated
   */
  CommandPlat createCommandPlat();

  /**
   * Returns a new object of class '<em>Operation Glob Call Old</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Operation Glob Call Old</em>'.
   * @generated
   */
  OperationGlobCallOld createOperationGlobCallOld();

  /**
   * Returns a new object of class '<em>Entity Glob Call</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Entity Glob Call</em>'.
   * @generated
   */
  EntityGlobCall createEntityGlobCall();

  /**
   * Returns a new object of class '<em>Operation Glob Call</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Operation Glob Call</em>'.
   * @generated
   */
  OperationGlobCall createOperationGlobCall();

  /**
   * Returns a new object of class '<em>Operation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Operation</em>'.
   * @generated
   */
  Operation createOperation();

  /**
   * Returns a new object of class '<em>Operation Global Old</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Operation Global Old</em>'.
   * @generated
   */
  OperationGlobalOld createOperationGlobalOld();

  /**
   * Returns a new object of class '<em>Entity Global</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Entity Global</em>'.
   * @generated
   */
  EntityGlobal createEntityGlobal();

  /**
   * Returns a new object of class '<em>Operation Global</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Operation Global</em>'.
   * @generated
   */
  OperationGlobal createOperationGlobal();

  /**
   * Returns a new object of class '<em>Attribute</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Attribute</em>'.
   * @generated
   */
  Attribute createAttribute();

  /**
   * Returns a new object of class '<em>Param List</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Param List</em>'.
   * @generated
   */
  ParamList createParamList();

  /**
   * Returns a new object of class '<em>DSL Type Ref</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>DSL Type Ref</em>'.
   * @generated
   */
  DSLTypeRef createDSLTypeRef();

  /**
   * Returns a new object of class '<em>DSL Concrete Type Ref</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>DSL Concrete Type Ref</em>'.
   * @generated
   */
  DSLConcreteTypeRef createDSLConcreteTypeRef();

  /**
   * Returns a new object of class '<em>DSL Generic Type Ref</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>DSL Generic Type Ref</em>'.
   * @generated
   */
  DSLGenericTypeRef createDSLGenericTypeRef();

  /**
   * Returns a new object of class '<em>DSL Generic Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>DSL Generic Type</em>'.
   * @generated
   */
  DSLGenericType createDSLGenericType();

  /**
   * Returns a new object of class '<em>Parameter</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Parameter</em>'.
   * @generated
   */
  Parameter createParameter();

  /**
   * Returns a new object of class '<em>Command Operation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Command Operation</em>'.
   * @generated
   */
  CommandOperation createCommandOperation();

  /**
   * Returns a new object of class '<em>Special Command</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Special Command</em>'.
   * @generated
   */
  SpecialCommand createSpecialCommand();

  /**
   * Returns a new object of class '<em>String Template Free Cod</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>String Template Free Cod</em>'.
   * @generated
   */
  StringTemplateFreeCod createStringTemplateFreeCod();

  /**
   * Returns a new object of class '<em>Abrev Cmd</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Abrev Cmd</em>'.
   * @generated
   */
  AbrevCmd createAbrevCmd();

  /**
   * Returns a new object of class '<em>Method Call Cmd</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Method Call Cmd</em>'.
   * @generated
   */
  MethodCallCmd createMethodCallCmd();

  /**
   * Returns a new object of class '<em>Vector</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Vector</em>'.
   * @generated
   */
  Vector createVector();

  /**
   * Returns a new object of class '<em>Call Attribute Object</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Call Attribute Object</em>'.
   * @generated
   */
  CallAttributeObject createCallAttributeObject();

  /**
   * Returns a new object of class '<em>Method Call Global</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Method Call Global</em>'.
   * @generated
   */
  MethodCallGlobal createMethodCallGlobal();

  /**
   * Returns a new object of class '<em>Op Logico While</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Op Logico While</em>'.
   * @generated
   */
  OpLogicoWhile createOpLogicoWhile();

  /**
   * Returns a new object of class '<em>Op Logico Do While</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Op Logico Do While</em>'.
   * @generated
   */
  OpLogicoDoWhile createOpLogicoDoWhile();

  /**
   * Returns a new object of class '<em>Op Logico IF</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Op Logico IF</em>'.
   * @generated
   */
  OpLogicoIF createOpLogicoIF();

  /**
   * Returns a new object of class '<em>Op Else If</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Op Else If</em>'.
   * @generated
   */
  OpElseIf createOpElseIf();

  /**
   * Returns a new object of class '<em>Op Else</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Op Else</em>'.
   * @generated
   */
  OpElse createOpElse();

  /**
   * Returns a new object of class '<em>Expr Logica</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expr Logica</em>'.
   * @generated
   */
  ExprLogica createExprLogica();

  /**
   * Returns a new object of class '<em>Termo Logico</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Termo Logico</em>'.
   * @generated
   */
  TermoLogico createTermoLogico();

  /**
   * Returns a new object of class '<em>Fator Logico</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Fator Logico</em>'.
   * @generated
   */
  FatorLogico createFatorLogico();

  /**
   * Returns a new object of class '<em>Com Log</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Com Log</em>'.
   * @generated
   */
  ComLog createComLog();

  /**
   * Returns a new object of class '<em>Expr L</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expr L</em>'.
   * @generated
   */
  ExprL createExprL();

  /**
   * Returns a new object of class '<em>Attrib ID</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Attrib ID</em>'.
   * @generated
   */
  AttribID createAttribID();

  /**
   * Returns a new object of class '<em>Op Logico For</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Op Logico For</em>'.
   * @generated
   */
  OpLogicoFor createOpLogicoFor();

  /**
   * Returns a new object of class '<em>Expr Logic For</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expr Logic For</em>'.
   * @generated
   */
  ExprLogicFor createExprLogicFor();

  /**
   * Returns a new object of class '<em>Assignment Cmd For</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Assignment Cmd For</em>'.
   * @generated
   */
  AssignmentCmdFor createAssignmentCmdFor();

  /**
   * Returns a new object of class '<em>Expr Arit</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expr Arit</em>'.
   * @generated
   */
  ExprArit createExprArit();

  /**
   * Returns a new object of class '<em>Termo</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Termo</em>'.
   * @generated
   */
  Termo createTermo();

  /**
   * Returns a new object of class '<em>Fator</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Fator</em>'.
   * @generated
   */
  Fator createFator();

  /**
   * Returns a new object of class '<em>Op Logico</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Op Logico</em>'.
   * @generated
   */
  OpLogico createOpLogico();

  /**
   * Returns a new object of class '<em>Method Call Op</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Method Call Op</em>'.
   * @generated
   */
  MethodCallOp createMethodCallOp();

  /**
   * Returns a new object of class '<em>Method Call Glob</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Method Call Glob</em>'.
   * @generated
   */
  MethodCallGlob createMethodCallGlob();

  /**
   * Returns a new object of class '<em>Attribute Call</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Attribute Call</em>'.
   * @generated
   */
  AttributeCall createAttributeCall();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  CrossPlatformPackage getCrossPlatformPackage();

} //CrossPlatformFactory
