/**
 * generated by Xtext 2.24.0
 */
package br.dslcross.crossplatform.crossPlatform;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>DSL Concrete Type Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.dslcross.crossplatform.crossPlatform.DSLConcreteTypeRef#getRef <em>Ref</em>}</li>
 * </ul>
 *
 * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getDSLConcreteTypeRef()
 * @model
 * @generated
 */
public interface DSLConcreteTypeRef extends DSLTypeRef
{
  /**
   * Returns the value of the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ref</em>' reference.
   * @see #setRef(Type)
   * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getDSLConcreteTypeRef_Ref()
   * @model
   * @generated
   */
  Type getRef();

  /**
   * Sets the value of the '{@link br.dslcross.crossplatform.crossPlatform.DSLConcreteTypeRef#getRef <em>Ref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ref</em>' reference.
   * @see #getRef()
   * @generated
   */
  void setRef(Type value);

} // DSLConcreteTypeRef
