/**
 * generated by Xtext 2.24.0
 */
package br.dslcross.crossplatform.crossPlatform;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expr Logic For</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.dslcross.crossplatform.crossPlatform.ExprLogicFor#getInicio <em>Inicio</em>}</li>
 *   <li>{@link br.dslcross.crossplatform.crossPlatform.ExprLogicFor#getCondicao <em>Condicao</em>}</li>
 *   <li>{@link br.dslcross.crossplatform.crossPlatform.ExprLogicFor#getAbrevCmd <em>Abrev Cmd</em>}</li>
 * </ul>
 *
 * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getExprLogicFor()
 * @model
 * @generated
 */
public interface ExprLogicFor extends EObject
{
  /**
   * Returns the value of the '<em><b>Inicio</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Inicio</em>' containment reference.
   * @see #setInicio(AssignmentCmdFor)
   * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getExprLogicFor_Inicio()
   * @model containment="true"
   * @generated
   */
  AssignmentCmdFor getInicio();

  /**
   * Sets the value of the '{@link br.dslcross.crossplatform.crossPlatform.ExprLogicFor#getInicio <em>Inicio</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Inicio</em>' containment reference.
   * @see #getInicio()
   * @generated
   */
  void setInicio(AssignmentCmdFor value);

  /**
   * Returns the value of the '<em><b>Condicao</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condicao</em>' containment reference.
   * @see #setCondicao(ExprLogica)
   * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getExprLogicFor_Condicao()
   * @model containment="true"
   * @generated
   */
  ExprLogica getCondicao();

  /**
   * Sets the value of the '{@link br.dslcross.crossplatform.crossPlatform.ExprLogicFor#getCondicao <em>Condicao</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condicao</em>' containment reference.
   * @see #getCondicao()
   * @generated
   */
  void setCondicao(ExprLogica value);

  /**
   * Returns the value of the '<em><b>Abrev Cmd</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Abrev Cmd</em>' containment reference.
   * @see #setAbrevCmd(CommandOperation)
   * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getExprLogicFor_AbrevCmd()
   * @model containment="true"
   * @generated
   */
  CommandOperation getAbrevCmd();

  /**
   * Sets the value of the '{@link br.dslcross.crossplatform.crossPlatform.ExprLogicFor#getAbrevCmd <em>Abrev Cmd</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Abrev Cmd</em>' containment reference.
   * @see #getAbrevCmd()
   * @generated
   */
  void setAbrevCmd(CommandOperation value);

} // ExprLogicFor
