/**
 * generated by Xtext 2.24.0
 */
package br.dslcross.crossplatform.crossPlatform;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expr Logica</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.dslcross.crossplatform.crossPlatform.ExprLogica#getTermos <em>Termos</em>}</li>
 *   <li>{@link br.dslcross.crossplatform.crossPlatform.ExprLogica#getOplog <em>Oplog</em>}</li>
 * </ul>
 *
 * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getExprLogica()
 * @model
 * @generated
 */
public interface ExprLogica extends EObject
{
  /**
   * Returns the value of the '<em><b>Termos</b></em>' containment reference list.
   * The list contents are of type {@link br.dslcross.crossplatform.crossPlatform.TermoLogico}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Termos</em>' containment reference list.
   * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getExprLogica_Termos()
   * @model containment="true"
   * @generated
   */
  EList<TermoLogico> getTermos();

  /**
   * Returns the value of the '<em><b>Oplog</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Oplog</em>' attribute list.
   * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getExprLogica_Oplog()
   * @model unique="false"
   * @generated
   */
  EList<String> getOplog();

} // ExprLogica
