/**
 * generated by Xtext 2.24.0
 */
package br.dslcross.crossplatform.crossPlatform;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Global Old</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.dslcross.crossplatform.crossPlatform.GlobalOld#getGenericTypes <em>Generic Types</em>}</li>
 *   <li>{@link br.dslcross.crossplatform.crossPlatform.GlobalOld#getParams <em>Params</em>}</li>
 *   <li>{@link br.dslcross.crossplatform.crossPlatform.GlobalOld#getType <em>Type</em>}</li>
 *   <li>{@link br.dslcross.crossplatform.crossPlatform.GlobalOld#getGenericTypesDecl <em>Generic Types Decl</em>}</li>
 *   <li>{@link br.dslcross.crossplatform.crossPlatform.GlobalOld#getCol1 <em>Col1</em>}</li>
 *   <li>{@link br.dslcross.crossplatform.crossPlatform.GlobalOld#getArray <em>Array</em>}</li>
 *   <li>{@link br.dslcross.crossplatform.crossPlatform.GlobalOld#getCol2 <em>Col2</em>}</li>
 * </ul>
 *
 * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getGlobalOld()
 * @model
 * @generated
 */
public interface GlobalOld extends Type
{
  /**
   * Returns the value of the '<em><b>Generic Types</b></em>' containment reference list.
   * The list contents are of type {@link br.dslcross.crossplatform.crossPlatform.DSLGenericType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Generic Types</em>' containment reference list.
   * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getGlobalOld_GenericTypes()
   * @model containment="true"
   * @generated
   */
  EList<DSLGenericType> getGenericTypes();

  /**
   * Returns the value of the '<em><b>Params</b></em>' containment reference list.
   * The list contents are of type {@link br.dslcross.crossplatform.crossPlatform.Parameter}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Params</em>' containment reference list.
   * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getGlobalOld_Params()
   * @model containment="true"
   * @generated
   */
  EList<Parameter> getParams();

  /**
   * Returns the value of the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' containment reference.
   * @see #setType(DSLTypeRef)
   * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getGlobalOld_Type()
   * @model containment="true"
   * @generated
   */
  DSLTypeRef getType();

  /**
   * Sets the value of the '{@link br.dslcross.crossplatform.crossPlatform.GlobalOld#getType <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' containment reference.
   * @see #getType()
   * @generated
   */
  void setType(DSLTypeRef value);

  /**
   * Returns the value of the '<em><b>Generic Types Decl</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Generic Types Decl</em>' containment reference.
   * @see #setGenericTypesDecl(DSLGenericType)
   * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getGlobalOld_GenericTypesDecl()
   * @model containment="true"
   * @generated
   */
  DSLGenericType getGenericTypesDecl();

  /**
   * Sets the value of the '{@link br.dslcross.crossplatform.crossPlatform.GlobalOld#getGenericTypesDecl <em>Generic Types Decl</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Generic Types Decl</em>' containment reference.
   * @see #getGenericTypesDecl()
   * @generated
   */
  void setGenericTypesDecl(DSLGenericType value);

  /**
   * Returns the value of the '<em><b>Col1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Col1</em>' attribute.
   * @see #setCol1(String)
   * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getGlobalOld_Col1()
   * @model
   * @generated
   */
  String getCol1();

  /**
   * Sets the value of the '{@link br.dslcross.crossplatform.crossPlatform.GlobalOld#getCol1 <em>Col1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Col1</em>' attribute.
   * @see #getCol1()
   * @generated
   */
  void setCol1(String value);

  /**
   * Returns the value of the '<em><b>Array</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Array</em>' attribute.
   * @see #setArray(int)
   * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getGlobalOld_Array()
   * @model
   * @generated
   */
  int getArray();

  /**
   * Sets the value of the '{@link br.dslcross.crossplatform.crossPlatform.GlobalOld#getArray <em>Array</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Array</em>' attribute.
   * @see #getArray()
   * @generated
   */
  void setArray(int value);

  /**
   * Returns the value of the '<em><b>Col2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Col2</em>' attribute.
   * @see #setCol2(String)
   * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getGlobalOld_Col2()
   * @model
   * @generated
   */
  String getCol2();

  /**
   * Sets the value of the '{@link br.dslcross.crossplatform.crossPlatform.GlobalOld#getCol2 <em>Col2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Col2</em>' attribute.
   * @see #getCol2()
   * @generated
   */
  void setCol2(String value);

} // GlobalOld
