/**
 * generated by Xtext 2.24.0
 */
package br.dslcross.crossplatform.crossPlatform;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Method Call Glob</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.dslcross.crossplatform.crossPlatform.MethodCallGlob#getObj <em>Obj</em>}</li>
 *   <li>{@link br.dslcross.crossplatform.crossPlatform.MethodCallGlob#getCalledOpGlobal <em>Called Op Global</em>}</li>
 *   <li>{@link br.dslcross.crossplatform.crossPlatform.MethodCallGlob#getArgs <em>Args</em>}</li>
 * </ul>
 *
 * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getMethodCallGlob()
 * @model
 * @generated
 */
public interface MethodCallGlob extends EObject
{
  /**
   * Returns the value of the '<em><b>Obj</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Obj</em>' reference.
   * @see #setObj(Attribute)
   * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getMethodCallGlob_Obj()
   * @model
   * @generated
   */
  Attribute getObj();

  /**
   * Sets the value of the '{@link br.dslcross.crossplatform.crossPlatform.MethodCallGlob#getObj <em>Obj</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Obj</em>' reference.
   * @see #getObj()
   * @generated
   */
  void setObj(Attribute value);

  /**
   * Returns the value of the '<em><b>Called Op Global</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Called Op Global</em>' reference.
   * @see #setCalledOpGlobal(Global)
   * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getMethodCallGlob_CalledOpGlobal()
   * @model
   * @generated
   */
  Global getCalledOpGlobal();

  /**
   * Sets the value of the '{@link br.dslcross.crossplatform.crossPlatform.MethodCallGlob#getCalledOpGlobal <em>Called Op Global</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Called Op Global</em>' reference.
   * @see #getCalledOpGlobal()
   * @generated
   */
  void setCalledOpGlobal(Global value);

  /**
   * Returns the value of the '<em><b>Args</b></em>' containment reference list.
   * The list contents are of type {@link br.dslcross.crossplatform.crossPlatform.AttributeCall}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Args</em>' containment reference list.
   * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getMethodCallGlob_Args()
   * @model containment="true"
   * @generated
   */
  EList<AttributeCall> getArgs();

} // MethodCallGlob
