/**
 * generated by Xtext 2.24.0
 */
package br.dslcross.crossplatform.crossPlatform;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Method Call Global</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.dslcross.crossplatform.crossPlatform.MethodCallGlobal#getCall1 <em>Call1</em>}</li>
 *   <li>{@link br.dslcross.crossplatform.crossPlatform.MethodCallGlobal#getCall2 <em>Call2</em>}</li>
 * </ul>
 *
 * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getMethodCallGlobal()
 * @model
 * @generated
 */
public interface MethodCallGlobal extends CommandOperation
{
  /**
   * Returns the value of the '<em><b>Call1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Call1</em>' containment reference.
   * @see #setCall1(MethodCallGlob)
   * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getMethodCallGlobal_Call1()
   * @model containment="true"
   * @generated
   */
  MethodCallGlob getCall1();

  /**
   * Sets the value of the '{@link br.dslcross.crossplatform.crossPlatform.MethodCallGlobal#getCall1 <em>Call1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Call1</em>' containment reference.
   * @see #getCall1()
   * @generated
   */
  void setCall1(MethodCallGlob value);

  /**
   * Returns the value of the '<em><b>Call2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Call2</em>' containment reference.
   * @see #setCall2(MethodCallOp)
   * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getMethodCallGlobal_Call2()
   * @model containment="true"
   * @generated
   */
  MethodCallOp getCall2();

  /**
   * Sets the value of the '{@link br.dslcross.crossplatform.crossPlatform.MethodCallGlobal#getCall2 <em>Call2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Call2</em>' containment reference.
   * @see #getCall2()
   * @generated
   */
  void setCall2(MethodCallOp value);

} // MethodCallGlobal
