/**
 * generated by Xtext 2.24.0
 */
package br.dslcross.crossplatform.crossPlatform;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operation Global</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.dslcross.crossplatform.crossPlatform.OperationGlobal#getGenericTypes <em>Generic Types</em>}</li>
 *   <li>{@link br.dslcross.crossplatform.crossPlatform.OperationGlobal#getParamList <em>Param List</em>}</li>
 *   <li>{@link br.dslcross.crossplatform.crossPlatform.OperationGlobal#getOpGlobal <em>Op Global</em>}</li>
 *   <li>{@link br.dslcross.crossplatform.crossPlatform.OperationGlobal#getParams <em>Params</em>}</li>
 *   <li>{@link br.dslcross.crossplatform.crossPlatform.OperationGlobal#getType <em>Type</em>}</li>
 *   <li>{@link br.dslcross.crossplatform.crossPlatform.OperationGlobal#getGenericTypesDecl <em>Generic Types Decl</em>}</li>
 *   <li>{@link br.dslcross.crossplatform.crossPlatform.OperationGlobal#getCol1 <em>Col1</em>}</li>
 *   <li>{@link br.dslcross.crossplatform.crossPlatform.OperationGlobal#getArray <em>Array</em>}</li>
 *   <li>{@link br.dslcross.crossplatform.crossPlatform.OperationGlobal#getCol2 <em>Col2</em>}</li>
 *   <li>{@link br.dslcross.crossplatform.crossPlatform.OperationGlobal#getCmdList <em>Cmd List</em>}</li>
 * </ul>
 *
 * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getOperationGlobal()
 * @model
 * @generated
 */
public interface OperationGlobal extends CommandPlat
{
  /**
   * Returns the value of the '<em><b>Generic Types</b></em>' containment reference list.
   * The list contents are of type {@link br.dslcross.crossplatform.crossPlatform.DSLGenericType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Generic Types</em>' containment reference list.
   * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getOperationGlobal_GenericTypes()
   * @model containment="true"
   * @generated
   */
  EList<DSLGenericType> getGenericTypes();

  /**
   * Returns the value of the '<em><b>Param List</b></em>' containment reference list.
   * The list contents are of type {@link br.dslcross.crossplatform.crossPlatform.ParamList}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Param List</em>' containment reference list.
   * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getOperationGlobal_ParamList()
   * @model containment="true"
   * @generated
   */
  EList<ParamList> getParamList();

  /**
   * Returns the value of the '<em><b>Op Global</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op Global</em>' reference.
   * @see #setOpGlobal(Global)
   * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getOperationGlobal_OpGlobal()
   * @model
   * @generated
   */
  Global getOpGlobal();

  /**
   * Sets the value of the '{@link br.dslcross.crossplatform.crossPlatform.OperationGlobal#getOpGlobal <em>Op Global</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op Global</em>' reference.
   * @see #getOpGlobal()
   * @generated
   */
  void setOpGlobal(Global value);

  /**
   * Returns the value of the '<em><b>Params</b></em>' containment reference list.
   * The list contents are of type {@link br.dslcross.crossplatform.crossPlatform.Parameter}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Params</em>' containment reference list.
   * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getOperationGlobal_Params()
   * @model containment="true"
   * @generated
   */
  EList<Parameter> getParams();

  /**
   * Returns the value of the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' containment reference.
   * @see #setType(DSLTypeRef)
   * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getOperationGlobal_Type()
   * @model containment="true"
   * @generated
   */
  DSLTypeRef getType();

  /**
   * Sets the value of the '{@link br.dslcross.crossplatform.crossPlatform.OperationGlobal#getType <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' containment reference.
   * @see #getType()
   * @generated
   */
  void setType(DSLTypeRef value);

  /**
   * Returns the value of the '<em><b>Generic Types Decl</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Generic Types Decl</em>' containment reference.
   * @see #setGenericTypesDecl(DSLGenericType)
   * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getOperationGlobal_GenericTypesDecl()
   * @model containment="true"
   * @generated
   */
  DSLGenericType getGenericTypesDecl();

  /**
   * Sets the value of the '{@link br.dslcross.crossplatform.crossPlatform.OperationGlobal#getGenericTypesDecl <em>Generic Types Decl</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Generic Types Decl</em>' containment reference.
   * @see #getGenericTypesDecl()
   * @generated
   */
  void setGenericTypesDecl(DSLGenericType value);

  /**
   * Returns the value of the '<em><b>Col1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Col1</em>' attribute.
   * @see #setCol1(String)
   * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getOperationGlobal_Col1()
   * @model
   * @generated
   */
  String getCol1();

  /**
   * Sets the value of the '{@link br.dslcross.crossplatform.crossPlatform.OperationGlobal#getCol1 <em>Col1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Col1</em>' attribute.
   * @see #getCol1()
   * @generated
   */
  void setCol1(String value);

  /**
   * Returns the value of the '<em><b>Array</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Array</em>' attribute.
   * @see #setArray(int)
   * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getOperationGlobal_Array()
   * @model
   * @generated
   */
  int getArray();

  /**
   * Sets the value of the '{@link br.dslcross.crossplatform.crossPlatform.OperationGlobal#getArray <em>Array</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Array</em>' attribute.
   * @see #getArray()
   * @generated
   */
  void setArray(int value);

  /**
   * Returns the value of the '<em><b>Col2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Col2</em>' attribute.
   * @see #setCol2(String)
   * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getOperationGlobal_Col2()
   * @model
   * @generated
   */
  String getCol2();

  /**
   * Sets the value of the '{@link br.dslcross.crossplatform.crossPlatform.OperationGlobal#getCol2 <em>Col2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Col2</em>' attribute.
   * @see #getCol2()
   * @generated
   */
  void setCol2(String value);

  /**
   * Returns the value of the '<em><b>Cmd List</b></em>' containment reference list.
   * The list contents are of type {@link br.dslcross.crossplatform.crossPlatform.CommandOperation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cmd List</em>' containment reference list.
   * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getOperationGlobal_CmdList()
   * @model containment="true"
   * @generated
   */
  EList<CommandOperation> getCmdList();

} // OperationGlobal
