/**
 * generated by Xtext 2.24.0
 */
package br.dslcross.crossplatform.crossPlatform;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Platform</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.dslcross.crossplatform.crossPlatform.Platform#getEnt <em>Ent</em>}</li>
 *   <li>{@link br.dslcross.crossplatform.crossPlatform.Platform#getPlat <em>Plat</em>}</li>
 *   <li>{@link br.dslcross.crossplatform.crossPlatform.Platform#getCommunication <em>Communication</em>}</li>
 *   <li>{@link br.dslcross.crossplatform.crossPlatform.Platform#getEntityEspecification <em>Entity Especification</em>}</li>
 * </ul>
 *
 * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getPlatform()
 * @model
 * @generated
 */
public interface Platform extends EObject
{
  /**
   * Returns the value of the '<em><b>Ent</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ent</em>' reference.
   * @see #setEnt(Entity)
   * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getPlatform_Ent()
   * @model
   * @generated
   */
  Entity getEnt();

  /**
   * Sets the value of the '{@link br.dslcross.crossplatform.crossPlatform.Platform#getEnt <em>Ent</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ent</em>' reference.
   * @see #getEnt()
   * @generated
   */
  void setEnt(Entity value);

  /**
   * Returns the value of the '<em><b>Plat</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Plat</em>' reference.
   * @see #setPlat(PlatformDecl)
   * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getPlatform_Plat()
   * @model
   * @generated
   */
  PlatformDecl getPlat();

  /**
   * Sets the value of the '{@link br.dslcross.crossplatform.crossPlatform.Platform#getPlat <em>Plat</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Plat</em>' reference.
   * @see #getPlat()
   * @generated
   */
  void setPlat(PlatformDecl value);

  /**
   * Returns the value of the '<em><b>Communication</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Communication</em>' attribute.
   * @see #setCommunication(String)
   * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getPlatform_Communication()
   * @model
   * @generated
   */
  String getCommunication();

  /**
   * Sets the value of the '{@link br.dslcross.crossplatform.crossPlatform.Platform#getCommunication <em>Communication</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Communication</em>' attribute.
   * @see #getCommunication()
   * @generated
   */
  void setCommunication(String value);

  /**
   * Returns the value of the '<em><b>Entity Especification</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entity Especification</em>' containment reference.
   * @see #setEntityEspecification(EntityEsp)
   * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getPlatform_EntityEspecification()
   * @model containment="true"
   * @generated
   */
  EntityEsp getEntityEspecification();

  /**
   * Sets the value of the '{@link br.dslcross.crossplatform.crossPlatform.Platform#getEntityEspecification <em>Entity Especification</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entity Especification</em>' containment reference.
   * @see #getEntityEspecification()
   * @generated
   */
  void setEntityEspecification(EntityEsp value);

} // Platform
