/**
 * generated by Xtext 2.24.0
 */
package br.dslcross.crossplatform.crossPlatform;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Platform Decl</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.dslcross.crossplatform.crossPlatform.PlatformDecl#getBase <em>Base</em>}</li>
 *   <li>{@link br.dslcross.crossplatform.crossPlatform.PlatformDecl#getCmdList <em>Cmd List</em>}</li>
 * </ul>
 *
 * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getPlatformDecl()
 * @model
 * @generated
 */
public interface PlatformDecl extends Type
{
  /**
   * Returns the value of the '<em><b>Base</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Base</em>' attribute.
   * @see #setBase(String)
   * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getPlatformDecl_Base()
   * @model
   * @generated
   */
  String getBase();

  /**
   * Sets the value of the '{@link br.dslcross.crossplatform.crossPlatform.PlatformDecl#getBase <em>Base</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Base</em>' attribute.
   * @see #getBase()
   * @generated
   */
  void setBase(String value);

  /**
   * Returns the value of the '<em><b>Cmd List</b></em>' containment reference list.
   * The list contents are of type {@link br.dslcross.crossplatform.crossPlatform.CommandPlat}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cmd List</em>' containment reference list.
   * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getPlatformDecl_CmdList()
   * @model containment="true"
   * @generated
   */
  EList<CommandPlat> getCmdList();

} // PlatformDecl
