/**
 * generated by Xtext 2.24.0
 */
package br.dslcross.crossplatform.crossPlatform;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Special Command</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.dslcross.crossplatform.crossPlatform.SpecialCommand#getCommand <em>Command</em>}</li>
 *   <li>{@link br.dslcross.crossplatform.crossPlatform.SpecialCommand#getAttr <em>Attr</em>}</li>
 *   <li>{@link br.dslcross.crossplatform.crossPlatform.SpecialCommand#getCommandCont <em>Command Cont</em>}</li>
 * </ul>
 *
 * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getSpecialCommand()
 * @model
 * @generated
 */
public interface SpecialCommand extends CommandOperation
{
  /**
   * Returns the value of the '<em><b>Command</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Command</em>' attribute.
   * @see #setCommand(String)
   * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getSpecialCommand_Command()
   * @model
   * @generated
   */
  String getCommand();

  /**
   * Sets the value of the '{@link br.dslcross.crossplatform.crossPlatform.SpecialCommand#getCommand <em>Command</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Command</em>' attribute.
   * @see #getCommand()
   * @generated
   */
  void setCommand(String value);

  /**
   * Returns the value of the '<em><b>Attr</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attr</em>' reference.
   * @see #setAttr(Attribute)
   * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getSpecialCommand_Attr()
   * @model
   * @generated
   */
  Attribute getAttr();

  /**
   * Sets the value of the '{@link br.dslcross.crossplatform.crossPlatform.SpecialCommand#getAttr <em>Attr</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Attr</em>' reference.
   * @see #getAttr()
   * @generated
   */
  void setAttr(Attribute value);

  /**
   * Returns the value of the '<em><b>Command Cont</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Command Cont</em>' attribute.
   * @see #setCommandCont(String)
   * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getSpecialCommand_CommandCont()
   * @model
   * @generated
   */
  String getCommandCont();

  /**
   * Sets the value of the '{@link br.dslcross.crossplatform.crossPlatform.SpecialCommand#getCommandCont <em>Command Cont</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Command Cont</em>' attribute.
   * @see #getCommandCont()
   * @generated
   */
  void setCommandCont(String value);

} // SpecialCommand
