/**
 * generated by Xtext 2.24.0
 */
package br.dslcross.crossplatform.crossPlatform;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Termo</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.dslcross.crossplatform.crossPlatform.Termo#getFatores <em>Fatores</em>}</li>
 *   <li>{@link br.dslcross.crossplatform.crossPlatform.Termo#getOp <em>Op</em>}</li>
 * </ul>
 *
 * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getTermo()
 * @model
 * @generated
 */
public interface Termo extends EObject
{
  /**
   * Returns the value of the '<em><b>Fatores</b></em>' containment reference list.
   * The list contents are of type {@link br.dslcross.crossplatform.crossPlatform.Fator}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fatores</em>' containment reference list.
   * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getTermo_Fatores()
   * @model containment="true"
   * @generated
   */
  EList<Fator> getFatores();

  /**
   * Returns the value of the '<em><b>Op</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op</em>' attribute list.
   * @see br.dslcross.crossplatform.crossPlatform.CrossPlatformPackage#getTermo_Op()
   * @model unique="false"
   * @generated
   */
  EList<String> getOp();

} // Termo
