/*
 * generated by Xtext 2.24.0
 */
package br.dslcross.crossplatform.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractCrossPlatformScopeProvider extends DelegatingScopeProvider {
}
